//
// Created by Admin on 05.06.2024.
//

#ifndef MAGICIANFEST_PLAYERCONTROLLEDMOVEMENT_H
#define MAGICIANFEST_PLAYERCONTROLLEDMOVEMENT_H


class PlayerControlledMovement {

};


#endif //MAGICIANFEST_PLAYERCONTROLLEDMOVEMENT_H
